/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

/**
 *
 * @author dell
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addstudentBtn1 = new javax.swing.JButton();
        addstudentBtn5 = new javax.swing.JButton();
        addstudentBtn3 = new javax.swing.JButton();
        addstudentBtn4 = new javax.swing.JButton();
        addstudentBtn2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 68)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("JAPALEARN INSTITUTE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, -1, 80));

        addstudentBtn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addstudentBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addstudentBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home imgs/309049_add_user_human_person_plus_icon.png"))); // NOI18N
        addstudentBtn1.setText("Add Student");
        addstudentBtn1.setBorder(null);
        addstudentBtn1.setBorderPainted(false);
        addstudentBtn1.setContentAreaFilled(false);
        addstudentBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(addstudentBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 220, 70));

        addstudentBtn5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addstudentBtn5.setForeground(new java.awt.Color(255, 255, 255));
        addstudentBtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home imgs/103539_edit_icon.png"))); // NOI18N
        addstudentBtn5.setText("Update & Delete");
        addstudentBtn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addstudentBtn5.setBorderPainted(false);
        addstudentBtn5.setContentAreaFilled(false);
        addstudentBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(addstudentBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 270, 70));

        addstudentBtn3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addstudentBtn3.setForeground(new java.awt.Color(255, 255, 255));
        addstudentBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home imgs/1564512_burger_catalogue_list_menu_icon.png"))); // NOI18N
        addstudentBtn3.setText("List of Student");
        addstudentBtn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addstudentBtn3.setBorderPainted(false);
        addstudentBtn3.setContentAreaFilled(false);
        addstudentBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(addstudentBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 270, 70));

        addstudentBtn4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addstudentBtn4.setForeground(new java.awt.Color(255, 255, 255));
        addstudentBtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home imgs/8673582_ic_fluent_payment_filled_icon.png"))); // NOI18N
        addstudentBtn4.setText("Payment");
        addstudentBtn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addstudentBtn4.setBorderPainted(false);
        addstudentBtn4.setContentAreaFilled(false);
        addstudentBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(addstudentBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 250, 70));

        addstudentBtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addstudentBtn2.setForeground(new java.awt.Color(255, 255, 255));
        addstudentBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home imgs/7030313_sign out_ui basic_logout_app_user interface_icon.png"))); // NOI18N
        addstudentBtn2.setText("Logout");
        addstudentBtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addstudentBtn2.setBorderPainted(false);
        addstudentBtn2.setContentAreaFilled(false);
        addstudentBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(addstudentBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 230, 70));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 770, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home imgs/japan-landscape-vector-minimalist-4k-y6.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1620, 830));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 830));

        setSize(new java.awt.Dimension(1528, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addstudentBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtn1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddStudent().setVisible(true);
    }//GEN-LAST:event_addstudentBtn1ActionPerformed

    private void addstudentBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtn5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateDelete().setVisible(true);
    }//GEN-LAST:event_addstudentBtn5ActionPerformed

    private void addstudentBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtn3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ListofStudent().setVisible(true);
    }//GEN-LAST:event_addstudentBtn3ActionPerformed

    private void addstudentBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtn4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Payment().setVisible(true);
    }//GEN-LAST:event_addstudentBtn4ActionPerformed

    private void addstudentBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtn2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_addstudentBtn2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addstudentBtn1;
    private javax.swing.JButton addstudentBtn2;
    private javax.swing.JButton addstudentBtn3;
    private javax.swing.JButton addstudentBtn4;
    private javax.swing.JButton addstudentBtn5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
